name: Roxi Auto Scraper

on:
  schedule:
    - cron: '*/20 * * * *' # প্রতি ২০ মিনিট পরপর চলবে
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false # ক্যাশ করা ক্রেডেনশিয়াল নিষ্ক্রিয় করা হলো

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraper
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TGITHUB_EMAIL: ${{ secrets.TGITHUB_EMAIL }}
          TGITHUB_REPO: ${{ secrets.TGITHUB_REPO }}
          TGITHUB_USER: ${{ secrets.TGITHUB_USER }}
        run: python roxi_scraper.py
